/**
 * System-prompt rules for writing concurrency-safe Ballerina code.
 *
 * These rules teach the agent to write code that satisfies the compiler's
 * IsolationAnalyzer up front (isolated functions/variables/objects, lock
 * statement restrictions, transfer in/out rules) so services are inferred
 * `isolated` and dispatched concurrently, and so the agent avoids the most
 * common isolation errors (BCE3943, BCE3956-BCE3964, BCE2080/BCE2081,
 * BCE4042/BCE4043) instead of hitting them and repairing after the fact.
 *
 * Also carries the lock/I-O rule (never perform I/O inside a lock; fan-out pattern that
 * compiles, verified on Ballerina 2201.13.4) and the immutable-clone rule (clone() of an
 * immutable value returns the same value; rebuild with a query expression + .clone() or
 * cloneWithType(), both verified on 2201.13.4).
 *
 * Kept in its own module (no imports) so it can be unit-tested without loading
 * the extension-host module graph. Interpolated into the system prompt by
 * getSystemPrompt() in ./prompts.ts.
 */
export const CONCURRENCY_CODING_RULES = `## Concurrency Safety and Shared State
Follow these rules when the code involves module-level state, service fields, or workers:
- \`configurable\` variables are implicitly final and safe to read from any isolated context — NEVER write \`final configurable\` (it is a compile error).
- For other module-level variables: if the value is never mutated, declare it \`final\`. A \`final\` module-level variable can be read from an \`isolated\` function or a service method WITHOUT a lock when its static type is immutable (\`readonly\`, e.g. \`final int[] & readonly defaults = [1, 2];\`) OR an isolated object — most connector clients and listeners (e.g. \`final http:Client httpClient = check new (url);\`), \`ai:Agent\`, and instances of your own \`isolated class\`. Do NOT declare such a variable \`isolated\`, do NOT wrap its use in \`lock { }\`, and do NOT add \`& readonly\` to it. For any OTHER type \`final\` alone is NOT sufficient: a \`final map<string>\` or \`final int[]\` is still non-isolated mutable state. If the state is shared and MUTABLE, declare the variable \`isolated\`, initialize it at its declaration (e.g. \`isolated int[] requests = [];\`), and access it ONLY inside \`lock { }\` blocks.
- In a service or class holding mutable state (declare such a class \`isolated class\` when a module-level \`final\` variable will hold it), declare every mutable field \`private\`, initialize it with a fresh literal/constructor, and access it via \`self\` ONLY inside \`lock { }\` blocks. For concurrent dispatch, each resource/remote method must ALSO satisfy isolated-function rules itself: call only \`isolated\` functions and never touch non-final module-level mutable state (use \`isolated\` variables with \`lock { }\` for that); the compiler then infers both the service and its methods as \`isolated\`.
- One \`lock\` block may protect only ONE isolated root: never access two \`isolated\` variables (or an \`isolated\` variable plus \`self\`) in the same lock — use separate lock statements and pass values between them via local variables. If two pieces of state must change together atomically, store them in ONE protected value (a single record/map behind one isolated variable).
- A lock that touches an isolated root (an \`isolated\` variable or \`self\` of an isolated object) may transfer OUT only an isolated expression — a \`readonly\` value or a SINGLE isolated object such as one \`websocket:Caller\`. Immutable (\`readonly\`) values and single isolated objects (a client, a caller) may cross the boundary freely; a MUTABLE value leaving the lock (returned or assigned to an outer variable) must not alias the protected state: copy it with \`value.clone()\` (or \`value.cloneReadOnly()\` when an immutable result is acceptable). An ARRAY or MAP of callers is NOT isolated: \`lock { targets = subscribers.toArray(); }\` fails to compile (BCE3959), and \`.clone()\` does not apply to objects. Do NOT make a value \`readonly\` merely to bring it into a lock when it will later be stored as mutable state — see the rule below on cloning an immutable value. An ordinary lock over non-isolated state has no such transfer restrictions — do not add gratuitous clones there.
- Never use \`start\`, named \`worker\` declarations, or worker send/receive actions (\`->\`/\`<-\`) inside a \`lock\` block. Read the needed values into locals inside the lock, then do the async work after it.
- Functions called from an \`isolated\` function, or from inside a lock protecting isolated state, must themselves be \`isolated\`. Write helper functions as \`isolated\` when they only work on their parameters and local state.
- Keep lock blocks minimal — only the shared-state read/write belongs inside; NEVER perform I/O or remote calls (\`->writeMessage\`, HTTP/DB client calls, \`runtime:sleep\`) inside a \`lock\`. Fan-out pattern over an \`isolated\` map of callers — snapshot the KEYS, fetch one connection per short lock, write OUTSIDE the lock, clean up in another short lock:
Build the value being sent (\`event\`) before the loop, outside every lock, and pass it as \`readonly\` so it can enter the locks freely.
- \`clone()\` and \`cloneReadOnly()\` on an ALREADY immutable value return the SAME immutable value, NOT a mutable copy: a value you made \`readonly\` (a \`readonly & T\` parameter, a \`cloneReadOnly()\` result, a \`readonly\` record field) stays immutable after \`.clone()\`, and storing it in a mutable-typed field or variable makes a later \`push\`/member update panic at run time with \`{ballerina/lang.array}InvalidUpdate\` ("modification not allowed on readonly value") — diagnostics cannot catch this. Never store a readonly-derived value where later code will mutate it; to obtain genuinely mutable state from a readonly value, REBUILD it: \`string[] fresh = (from string q in roQueues select q).clone();\` — the trailing \`.clone()\` makes the expression an isolated expression, so this form also works when assigning straight to an \`isolated\` variable inside a lock (a bare query expression there is a compile error) — or, in a function that can return \`error\`, \`string[] fresh = check roQueues.cloneWithType();\`.`;
