/*
 *  Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com)
 *
 *  WSO2 LLC. licenses this file to you under the Apache License,
 *  Version 2.0 (the "License"); you may not use this file except
 *  in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */

package io.ballerina.modelgenerator.commons.trigger.models;

import java.util.List;

/**
 * Deserialization target for a connector's own <b>{@code resources/trigger-metadata.json}</b> — the
 * authoring-rules overlay that sits above the syntax tree and semantic model: presence rules,
 * {@code oneOf} cross-construct relationships, identifier/base-path semantics, and handler shapes for
 * service types with no concrete backing type.
 *
 * <p>Deliberately separate from {@link TriggerArtifactModel} (the existing, display-only
 * {@code resources/trigger-artifact.json} sibling used for tree-node name/icon/label) and from the
 * much larger, fully UI-ready {@code trigger-ui-schema.json} (a {@code TriggerUISchemaModel}
 * Property/codedata tree, hand-authored or generated by the {@code generate-trigger-model} tooling).
 * This document carries only what a coding agent or the language server <b>cannot</b> recover by
 * introspecting the library itself (per the governing DRY principle: everything the compiler API can
 * already tell you — a listener's init signature, a concrete service type's declared methods, an
 * annotation record's field shapes — is referenced by name here, never restated). A
 * {@link TriggerUISchemaModel}-equivalent is synthesized at request time by combining this document
 * with semantic-API introspection of the referenced types.
 *
 * <p>Omit {@link #annotations} / {@link #dataBindingRules} entirely when the connector has none — an
 * empty array is never used in their place, consistent with the rest of this schema: a field that
 * would be empty, unused, or fully derivable from other fields is left out.
 *
 * @param version          the spec version this instance conforms to, e.g. {@code "v1"}. Required by the
 *                         spec ("Bump it whenever a field's meaning changes incompatibly"), but
 *                         {@code null} for any document authored before the key existed — which is why
 *                         {@code SpecVersionGate} reads an absent version as acceptable-with-warning
 *                         rather than rejecting it
 * @param listeners        the connector's listener entry point(s); always at least one — a listener
 *                         is structurally required, so there is no presence marker on this array
 * @param serviceTypes     the connector's service-type alternatives. Exactly one entry means it is the
 *                         (only, required) service type; more than one entry means each is
 *                         individually optional and the choice of which to implement is left to
 *                         whatever supplied the generation intent
 * @param annotations      registry of annotation types referenced elsewhere in this document, defined
 *                         once; {@code null}/absent when the connector declares none
 * @param dataBindingRules registry of payload/data-binding modes referenced from
 *                         {@code serviceTypes[].handlers.options[].params[].dataBinding}, defined
 *                         once; {@code null}/absent when the connector declares none
 * @since 1.10.0
 */
public record TriggerMetadataModel(
        String version,
        List<Listener> listeners,
        List<ServiceType> serviceTypes,
        List<Annotation> annotations,
        List<DataBindingRule> dataBindingRules) {

    /**
     * A listener entry point. No init fields are ever modeled here — a listener's init signature is
     * introspectable (the governing DRY principle), so a generator gets real init parameters from the
     * library itself, not from this file. There is no {@code presence} field — a listener is always
     * structurally required.
     *
     * @param type            the listener class
     * @param services        the {@link ServiceType#id()} values this listener can host
     * @param requiredImports packages that must be imported for side effect even though nothing in the
     *                        generated code references them by name (e.g. a generic engine needing a
     *                        specific driver registered at runtime); {@code null}/absent when the
     *                        connector needs no such import
     */
    public record Listener(TypeRef type, List<String> services, List<RequiredImport> requiredImports) {
    }

    /**
     * A package that must be imported for its side effect (e.g. {@code import ballerinax/mssql.cdc.driver as _;})
     * even though nothing in the generated code references it by name.
     *
     * @param importType  the reason the import is required; {@link #IMPORT_TYPE_DRIVER} is the only
     *                    value seen in the corpus this schema was built against
     * @param packageInfo the coordinates of the package to import
     */
    public record RequiredImport(String importType, TypeRef.PackageInfo packageInfo) {

        public static final String IMPORT_TYPE_DRIVER = "driver";
    }

    /**
     * One service-type alternative a connector exposes, as declared in a {@code trigger-metadata.json}
     * document's {@code serviceTypes[]}. See {@link TriggerMetadataModel#serviceTypes()} for how array
     * cardinality (rather than a {@code presence} field) determines whether an entry is mandatory.
     *
     * @param id                                  local identifier, referenced from
     *                                            {@link Listener#services()} and from other service
     *                                            types' {@link Rule.RuleMember}s
     * @param type                                the service object type
     * @param concrete                            {@code true} if the type declares its own methods
     *                                            directly (fully introspectable — {@code handlers} then
     *                                            carries {@code backedByConcreteType: true} and no
     *                                            {@code options}); {@code false} for a marker/abstract type
     * @param multipleListenersAllowed            can one service instance attach to more than one
     *                                            listener in a single declaration ({@code service X on l1, l2 {}});
     *                                            boxed so an absent key stays {@code null} rather than
     *                                            deserializing to {@code false} — a consumer that states
     *                                            only the prohibition would otherwise turn an omission
     *                                            into a restriction the document never made
     * @param multipleServicesPerListenerAllowed  can one listener instance host more than one service of
     *                                            this type simultaneously; boxed for the same reason
     * @param identifier                          the identifier/base-path slot (the string/path after
     *                                            {@code service}); {@code null}/absent when the slot
     *                                            carries no meaning for this service type
     * @param handlers                            the handler catalog
     * @param rules                               cross-construct constraints scoped to this service type;
     *                                            {@code null}/absent when none apply
     * @since 1.10.0
     */
    public record ServiceType(
            String id,
            TypeRef type,
            boolean concrete,
            Boolean multipleListenersAllowed,
            Boolean multipleServicesPerListenerAllowed,
            PresenceForm identifier,
            Handlers handlers,
            List<Rule> rules) {

        /**
         * The handler catalog for one service type.
         *
         * @param backedByConcreteType {@code true} means the service type's own declared methods are the
         *                             handlers ({@code options} is empty/absent and nothing further is
         *                             specified — fully introspectable); {@code false} means the type
         *                             declares no legal handlers itself, so {@code options} is the only
         *                             source of truth
         * @param addMode              how many of {@code options} can/must be implemented at once; absent
         *                             when {@code backedByConcreteType} is {@code true}
         * @param options              the handler vocabulary; empty/absent when {@code backedByConcreteType}
         *                             is {@code true}
         */
        public record Handlers(boolean backedByConcreteType, String addMode, List<HandlerOption> options) {

            /** A fixed, named vocabulary; each option carries its own {@code presence}. */
            public static final String ADD_MODE_SUBSET = "subset";
            /** An open-ended, user-named set; represented as a single option named
             *  {@link HandlerOption#WILDCARD_NAME}. */
            public static final String ADD_MODE_MANY = "many";
        }

        /**
         * One handler in the catalog — either a named option under {@code addMode: "subset"}, or the
         * single {@link #WILDCARD_NAME} entry under {@code addMode: "many"}.
         *
         * @param name            the handler's method name, or {@link #WILDCARD_NAME} for an open/many-shaped handler
         * @param kind            {@link #KIND_REMOTE} or {@link #KIND_RESOURCE}
         * @param presence        meaningful only under {@code addMode: "subset"} —
         *                       {@code "required"}/{@code "optional"} for this specific named option
         * @param annotations     ids into {@link TriggerMetadataModel#annotations()} attached at
         *                        {@code attachPoint: "function"} for this handler
         * @param params          the handler's parameters, in meaningful positional order
         * @param returns         the handler's return type(s) — a union is expressed as more than one
         *                        element
         * @param method          resource-kind extra (HTTP): the legal HTTP verbs; {@code null} for a
         *                        remote-kind handler
         * @param path            resource-kind extra (HTTP): the legal path-segment shapes; {@code null}
         *                        for a remote-kind handler
         * @param accessor        resource-kind extra (GraphQL): {@code "get"} for a query field,
         *                        {@code "subscribe"} for a subscription; {@code null} otherwise
         * @param fieldName       resource-kind extra (GraphQL): the legal field-name shapes; {@code null}
         *                        otherwise
         * @param graphqlOperation resource-kind extra (GraphQL), informational: {@code "query"},
         *                        {@code "mutation"}, or {@code "subscription"}; {@code null} otherwise
         */
        public record HandlerOption(
                String name,
                String kind,
                String presence,
                List<String> annotations,
                List<Param> params,
                List<TypeRef> returns,
                PresenceValues method,
                PresenceForm path,
                PresenceValues accessor,
                PresenceForm fieldName,
                String graphqlOperation) {

            public static final String KIND_REMOTE = "remote";
            public static final String KIND_RESOURCE = "resource";
            public static final String WILDCARD_NAME = "*";
        }

        /**
         * One parameter slot of a {@link HandlerOption}. Order in the array is meaningful and is trusted
         * to convey positional constraints.
         *
         * @param name        the conventional/domain-meaningful parameter name; {@code null} when the
         *                    slot's name carries no meaning beyond its position
         * @param type        the parameter's legal type(s) — a union is expressed as more than one element
         * @param presence    {@code "required"} or {@code "optional"} for this slot
         * @param addMode     {@link Handlers#ADD_MODE_MANY} when this slot can repeat zero or more times,
         *                    each occurrence independently named/typed by the user; {@code null} means "at
         *                    most one"
         * @param dataBinding id into {@link TriggerMetadataModel#dataBindingRules()}; present only when
         *                    the raw value can be projected into a different, user-defined type
         * @param annotations ids into {@link TriggerMetadataModel#annotations()} attached at
         *                    {@code attachPoint: "parameter"} for this param
         */
        public record Param(
                String name,
                List<TypeRef> type,
                String presence,
                String addMode,
                String dataBinding,
                List<String> annotations) {
        }

        /**
         * A cross-construct constraint scoped to the enclosing service type. {@code type} lets new rule
         * kinds be added later without another shape change; spec §6 defines two today —
         * {@link #TYPE_ONE_OF} (exactly one of {@code members}, not zero and not more than one) and
         * {@link #TYPE_AT_MOST_ONE} (zero or one, never more).
         *
         * @param id      a local identifier for the rule, for diagnostics/documentation
         * @param type    the rule kind
         * @param members the mutually-exclusive alternatives
         */
        public record Rule(String id, String type, List<RuleMember> members) {

            public static final String TYPE_ONE_OF = "oneOf";
            /**
             * Spec §6: "Zero or one member — never more than one, but zero is fine." Used by
             * {@code websocket}'s two rules. Note the repo's own
             * {@code resources/schemas/trigger-metadata.schema.json} still declares
             * {@code enum: ["oneOf"]} for {@code rules[].type}, so those two documents currently fail
             * the repo's schema validation; widening the enum belongs to the validator phase.
             */
            public static final String TYPE_AT_MOST_ONE = "atMostOne";

            /**
             * One alternative in a {@link Rule#TYPE_ONE_OF} group. Exactly one of the three shapes is
             * populated per member: a field inside a top-level annotation's record
             * ({@code annotation} + {@code field}), the enclosing service type's own identifier slot
             * ({@code part: "identifier"}), or one of the enclosing service type's own
             * {@code handlers.options[].name} values ({@code handler}). A member never repeats the
             * enclosing service type's id — that's implicit from nesting.
             *
             * @param annotation id into {@link TriggerMetadataModel#annotations()}; set only for the
             *                   annotation-field alternative
             * @param field      the field name inside {@code annotation}'s record; set only alongside
             *                   {@code annotation}
             * @param preferred  {@code true} marks the canonical/idiomatic choice for a generator to
             *                   default to when nothing else disambiguates; {@code null} otherwise
             * @param part       {@link #PART_IDENTIFIER}; set only for the identifier alternative
             * @param handler    a {@link HandlerOption#name()} value; set only for the handler-choice
             *                   alternative
             */
            public record RuleMember(String annotation, String field, Boolean preferred, String part,
                                      String handler) {

                public static final String PART_IDENTIFIER = "identifier";
            }
        }
    }

    /**
     * One entry in a {@code trigger-metadata.json} document's top-level {@code annotations[]} registry —
     * an annotation type referenced elsewhere in the document (from a handler's or parameter's
     * {@code annotations} list, or from a {@link ServiceType.Rule.RuleMember#annotation()}),
     * defined once here rather than restated at each attachment point.
     *
     * <p>The annotation record's own field names, types, defaults, and enums are never restated — they
     * are introspectable from {@link #type()} itself (the governing DRY principle). This entry carries
     * only what isn't: whether the annotation must be attached at all, where it attaches, and — only when
     * no more precise reference already exists — which service type(s) it belongs to.
     *
     * @param id         referenced from {@code params[].annotations}, {@code handlers.options[].annotations},
     *                  or {@code rules[].members[].annotation}
     * @param type       the annotation type (may be cross-module — see {@link TypeRef})
     * @param attachPoint one of {@code "service"}, {@code "function"}, {@code "parameter"}, {@code "return"}
     * @param appliesTo  ids into {@link TriggerMetadataModel#serviceTypes()}; included only when nothing
     *                  else already links this annotation to a service type (no
     *                  {@code params[].annotations}, {@code handlers.options[].annotations}, or
     *                  {@code rules[].members[].annotation} reference exists) — such a reference is
     *                  strictly more precise, so {@code appliesTo} would be redundant alongside one.
     *                  {@code null}/absent when a more precise reference exists elsewhere
     * @param presence   {@code "required"} or {@code "optional"} — whether this annotation must be
     *                  attached at all
     * @since 1.10.0
     */
    public record Annotation(String id, TypeRef type, String attachPoint, List<String> appliesTo,
                              String presence) {

        public static final String ATTACH_POINT_SERVICE = "service";
        public static final String ATTACH_POINT_FUNCTION = "function";
        public static final String ATTACH_POINT_PARAMETER = "parameter";
        public static final String ATTACH_POINT_RETURN = "return";

        public static final String PRESENCE_REQUIRED = "required";
        public static final String PRESENCE_OPTIONAL = "optional";
    }

    /**
     * One entry in a {@code trigger-metadata.json} document's top-level {@code dataBindingRules[]}
     * registry — the legal ways a handler parameter's raw value can be projected into a different,
     * user-defined type (e.g. RabbitMQ/Kafka's envelope-inclusion, FTP's JSON/XML/CSV variants).
     * Referenced from {@link ServiceType.Param#dataBinding()}.
     *
     * @param id             referenced from {@code params[].dataBinding}
     * @param envelopeType   the record being wrapped; present only when {@code supportedModes} includes an
     *                      {@link SupportedMode#MODE_INCLUDED_RECORD} entry — restating it on that entry
     *                      too would either duplicate {@link SupportedMode#includes()} or falsely imply a
     *                      partial-envelope relationship where there is none (e.g. a rule with only
     *                      {@code direct}/{@code streamable} modes)
     * @param cardinality    {@link #CARDINALITY_ARRAY} when the bound value is actually an array/batch of
     *                      the described type (i.e. whatever a mode resolves to is the array element
     *                      type, not the param's whole type); {@code null} for a scalar,
     *                      one-value-per-invocation binding
     * @param supportedModes the legal binding modes for this slot
     * @since 1.10.0
     */
    public record DataBindingRule(String id, TypeRef envelopeType, String cardinality,
                                   List<SupportedMode> supportedModes) {

        public static final String CARDINALITY_ARRAY = "array";

        /**
         * One binding mode a {@link DataBindingRule} supports.
         *
         * @param mode          {@link #MODE_DIRECT}, {@link #MODE_INCLUDED_RECORD}, or
         *                     {@link #MODE_STREAMABLE}
         * @param typeConstraint the legal alternatives for {@link #MODE_DIRECT}/{@link #MODE_STREAMABLE};
         *                     {@code null} for {@link #MODE_INCLUDED_RECORD}
         * @param excludes      types that are members of {@code typeConstraint}'s general category but
         *                     explicitly disallowed (e.g. {@code anydata} excluding subtypes of the
         *                     envelope type); {@code null}/absent when nothing is excluded
         * @param includes      the base record being included via {@code *Type;}; set only for
         *                     {@link #MODE_INCLUDED_RECORD}
         * @param bindableFields the field names the user's record is free to override; set only for
         *                     {@link #MODE_INCLUDED_RECORD} — the complement (fields that stay pinned) is
         *                     always derivable from {@link #includes}'s own declared fields minus this
         *                     list, so it is never separately restated
         */
        public record SupportedMode(
                String mode,
                List<TypeRef> typeConstraint,
                List<TypeRef> excludes,
                TypeRef includes,
                List<String> bindableFields) {

            /** The param's type directly is the target type — no wrapping. */
            public static final String MODE_DIRECT = "direct";
            /** A user-defined record that does {@code *EnvelopeType;} plus overrides only {@code bindableFields}. */
            public static final String MODE_INCLUDED_RECORD = "includedRecord";
            /** Same as {@link #MODE_DIRECT}, but the param is a {@code stream<...>} over the target type. */
            public static final String MODE_STREAMABLE = "streamable";
        }
    }
}
